logger:
  path:                  "../data/log"            # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file:                  "cgManager2.log"                    # 日志文件格式。默认为"{Y-m-d}.log"
  level:                 "debug"         # 日志输出级别
  rotateSize:            "100M"        # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性(字节)
  rotateBackupLimit:     7             # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  rotateCheckInterval:   "1m"          # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时

# 基础设定
basic_setting:
  # 设备类型 "SERVER" "WG800" "EM500" "TCU1200"
  device_type: "WG800"
  # 指定SN码
  device_sn: ""

# 日志设定
log_setting:
  # 日志打印等级
  level: "debug"
  # 日志文件位置
  file_name: "../data/log/cgManager.log"
  # 单个文件最大大小 单位MB
  max_size: 16
  # 最多文件个数
  max_age: 3
  # 文件最长备份时间(天)
  max_backups: 28
  # 是否使用本地时区
  local_time: true
  # 是否压缩日志文件
  compress: true

# 服务设定
server_setting:
  # 获取设备的在线配置信息的地址
  online_config_address: "https://erp.2cifang.cn/api/box/erp/"
  # 订阅主题 %s为设备Serial Number
  subscribe_topics:
    erp: [
      "box/%s/box_restart",
      "box/%s/app_restart",
      "box/%s/app_up",
      "box/%s/box_sys_log_open",
      "box/%s/box_app_log_open",
      "box/%s/site_update"
    ]
    pro: [
      "channel/%s/site_op"
    ]

  # 通道订阅主题 %s为通道注册码 仅订阅到PRO平台
  channel_topics: [
    "channel/%s/zczt",
    "channel/%s/device_change",
    "channel/%s/site_update"
  ]
  connectivity_setting:
    tcp:
      port: 7210

# 数据库设定
leveldb:
  collect_data_path: "../data/leveldb/collect"    # levelDB 采集原始数据存储位置
  processed_data_path: "../data/leveldb/processed"    # levelDB 处理过的数据存储位置